/**
 * Copyright to the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */
package fitnesse.maven.util;

import fitnesse.maven.io.MavenCommandShell;
import fitnesse.maven.io.PomFile;
import junit.framework.TestCase;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.File;
import java.text.MessageFormat;


public class LocalRepoResolverTest extends TestCase {
    private static final PomFile POM = new PomFile(new File("blah/pom.xml"));
    private MavenCommandShell shell;
    private LocalRepoResolver resolver;

    protected void setUp() throws Exception {
        super.setUp();
        shell = mock(MavenCommandShell.class);
        resolver = new LocalRepoResolver(shell);
    }

    public void test_resolve_Unix() {
        String consoleOutput = goodResponse("/Users/dan/.m2/repository");

        when(shell.execute(POM, "help:effective-settings")).thenReturn(consoleOutput);

        assertEquals(new File("/Users/dan/.m2/repository"), resolver.resolve(POM));
    }

    public void test_resolve_Windows() {
        String consoleOutput = goodResponse("c:\\Users\\dan\\.m2\\repository");

        when(shell.execute(POM, "help:effective-settings")).thenReturn(consoleOutput);

        assertEquals(new File("c:\\Users\\dan\\.m2\\repository"), resolver.resolve(POM));
    }

    private String goodResponse(String filePath) {
        String consoleOutput = "[INFO] Scanning for projects...\n" +
                "[INFO] Searching repository for plugin with prefix: 'help'.\n" +
                "[INFO] ------------------------------------------------------------------------\n" +
                "[INFO] Building maven-fitnesse\n" +
                "[INFO]    task-segment: [help:effective-settings] (aggregator-style)\n" +
                "[INFO] ------------------------------------------------------------------------\n" +
                "[INFO] [help:effective-settings]\n" +
                "[INFO] \n" +
                "Effective user-specific configuration settings:\n" +
                "\n" +
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<!-- ====================================================================== -->\n" +
                "<!--                                                                        -->\n" +
                "<!-- Generated by Maven Help Plugin on 4/25/09 1:46 PM                      -->\n" +
                "<!-- See: http://maven.apache.org/plugins/maven-help-plugin/                -->\n" +
                "<!--                                                                        -->\n" +
                "<!-- ====================================================================== -->\n" +
                "\n" +
                "<!-- ====================================================================== -->\n" +
                "<!--                                                                        -->\n" +
                "<!-- Effective Settings for 'dan' on 'dan-dudleys-macbook.local'            -->\n" +
                "<!--                                                                        -->\n" +
                "<!-- ====================================================================== -->\n" +
                "\n" +
                "<settings xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\">\n" +
                "  <localRepository>{0}</localRepository>\n" +
                "</settings>\n" +
                "\n" +
                "[INFO] ------------------------------------------------------------------------\n" +
                "[INFO] BUILD SUCCESSFUL\n" +
                "[INFO] ------------------------------------------------------------------------\n" +
                "[INFO] Total time: 2 seconds\n" +
                "[INFO] Finished at: Sat Apr 25 13:46:53 CDT 2009\n" +
                "[INFO] Final Memory: 9M/23M\n" +
                "[INFO] ------------------------------------------------------------------------";
        return MessageFormat.format(consoleOutput, filePath);
    }


}
